# Generated by Django 4.2.1 on 2023-10-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("maxtemp", models.IntegerField(null=True)),
                ("mintemp", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
    ]
