# Generated by Django 4.2.1 on 2023-10-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_users_delete_createuser"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="users",
            table="users",
        ),
    ]
